version: '3.4'

services:
  eventstoressubscriber: 
    image: eventstoressubscriber
    build:
      context: .
      dockerfile: EventStore.Subscriber/Dockerfile
    depends_on:
    - eventstoresample
    - eventstore

  eventstoresample: 
    image: eventstoresample
    build:
      context: .
      dockerfile: EventStoreSample/Dockerfile
    depends_on:
    - eventstore

  eventstore: 
    image: eventstore/eventstore
    container_name: "es"
    environment:
      - EVENTSTORE_INT_IP=172.16.0.13
      - EVENTSTORE_EXT_HTTP_PORT=2113
      - EVENTSTORE_EXT_TCP_PORT=1113
      - EVENTSTORE_EXT_HTTP_PREFIXES=http://*:2113/
    ports:
      - "1113:1113"
      - "2113:2113"

  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=test
      - MONGO_INITDB_ROOT_PASSWORD=test
    ports:
      - "27014:27017"